### ISSUE TITLE
sub-process-fail

### ISSUE THREAD

**Issue by Lizzit** [itzg/mc-server-runner#28]
Hi! I'm tring to install on my ubuntu server the minecraft pack Stacia using docker with the following command: 
`docker run -it  -e EULA=TRUE  -p 25565:25565  -v /home/server/mc-docker:/data  -e TYPE=CURSEFORGE  -e CF_SERVER_MOD=https://media.forgecdn.net/files/3791/350/Stacia+Expert1.17.6_server_pack.zip  --name mc-stacia-server  itzg/minecraft-server -e MEMORYSIZE='7G'`

But the output is not very positive: 
`[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 3 1000 1000 4096 May 20 13:31 /data'
[init] Resolved version given LATEST into 1.18.2 and major version 1.18
[init] Resolving type given CURSEFORGE
[init] Looking for Feed-The-Beast / CurseForge server modpack.
[init] detected FTB, changing properties path to /data/FeedTheBeast/server.properties
[init] server.properties already created, skipping
[init] Checking for JSON files.
[init] Setting initial memory to 1G and max to 1G
[init] Running FTB /data/FeedTheBeast/ServerStart.sh in /data/FeedTheBeast ...
2022-05-20 13:43:32,211 main WARN Advanced terminal features are not available in this environment
[13:43:32] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.34, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, nogui]
[13:43:32] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 17.0.3 by Eclipse Adoptium
Exception in thread "main" java.lang.IllegalAccessError: class cpw.mods.modlauncher.SecureJarHandler (in unnamed module @0x76e37707) cannot access class sun.security.util.ManifestEntryVerifier (in module java.base) because module java.base does not export sun.security.util to unnamed module @0x76e37707
        at cpw.mods.modlauncher.SecureJarHandler.lambda$static$1(SecureJarHandler.java:45)
        at cpw.mods.modlauncher.api.LamdbaExceptionUtils.uncheck(LamdbaExceptionUtils.java:95)
        at cpw.mods.modlauncher.SecureJarHandler.<clinit>(SecureJarHandler.java:45)
        at cpw.mods.modlauncher.Launcher.lambda$new$6(Launcher.java:55)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
        at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:52)
        at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:47)
        at cpw.mods.modlauncher.Environment.computePropertyIfAbsent(Environment.java:62)
        at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:55)
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
2022-05-20T13:43:32.387Z        WARN    mc-server-runner        sub-process failed      {"exitCode": 1}
2022-05-20T13:43:32.387Z        INFO    mc-server-runner        Done`

Can someone explain me how to solve this?
(Sorry but i don't know how to format properly the output

**Comment by itzg** [comment]
For future reference, this should be reported at https://github.com/itzg/docker-minecraft-server/issues

That video is probably from before Java 17. Use one of the Java 8 images such as `itzg/minecraft-server:java8-multiarch`

**Comment by Lizzit** [comment]
Ok, thank you! Now I'll try and I'll let you know if it worked
